apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q0f5bsxzq-python 
  janus-idp.io/tekton: q0f5bsxzq-python
  backstage.io/kubernetes-id: q0f5bsxzq-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q0f5bsxzq-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml